spring.application.name=ingestion-service

server.port=9104

# Kafka
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.template.default-topic=energy-usage
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Continuous simulation configuration
simulation.endpoint=http://localhost:9104/api/v1/ingestions
simulation.requests-per-interval=1000
simulation.interval-ms=5000
simulator.parallel-threads=10