spring.application.name=insight-service

server.port=9106
usage.service.url=http://localhost:9083/api/v1/usages

spring.ai.ollama.chat.model=deepseek-coder
spring.ai.ollama.init.pull-model-strategy=never